### ISSUE TITLE
all download links of  Multimodal VoxCeleb Dataset are missing

### ISSUE THREAD

**Issue by lyk412** [snap-research/MMVID#10]
Hi! Could you update the link of the dataset ? Thanks!

**Comment by phymhan** [comment]
Hi! Thanks for your interest in our work! The original links were hosted on my university google drive which was unlimited at the time. Now there is a space limit so I had to delete those files. The preprocessed dataset has hundreds of GB and I unfortunately do not have a good place to host them. But you can always download from the official VoxCeleb1 and process by yourself (https://github.com/snap-research/MMVID/blob/main/mm_vox_celeb/README.md).

**Comment by lyk412** [comment]
Thanks so much for the reply and advice！
