### ISSUE TITLE
textual description generated for dependent multimodal generation

### ISSUE THREAD

**Issue by Crane-YU** [snap-research/MMVID#5]
Hi,

Thanks for sharing your great work. Can you please elaborate on how you generated the texts for dependent multimodal generation? Are you guys using a fixed template as MUG or Shapes? I might miss the details in your main work or supp, so it would be much appreciated if you can address my concern.

**Comment by phymhan** [comment]
Hi Crane-YU,

Thanks for your interest in our work! For now, these dependent texts are generated by templates and is hardcoded (sorry the current codebase is not fully-cleaned and optimized yet) in the dataloaders. For example:
[Multimodal-VoxCeleb](https://github.com/snap-research/MMVID/blob/585ce42f794bcbc50d853cedee03b7a95643f06a/mmvid_pytorch/loader_ext.py#L597)

[Shapes](https://github.com/snap-research/MMVID/blob/585ce42f794bcbc50d853cedee03b7a95643f06a/mmvid_pytorch/loader_ext.py#L1798)

Hope this helps!

**Comment by Crane-YU** [comment]
Hi @phymhan,

Thanks for your response.
